Added StarGeneratorTest.java
MetroCS/redistricting pull request #157
Opened 2021-12-07 20:18 UTC by 13Lena

Created an incomplete test class for StarGenerator.java

- The number of `Location` objects in each pattern is equivalent to some desired input `n`
- Each pattern is contiguous
- Each Location is unique within a particular pattern

We suggest breaking up `generatePatternTest` method into private methods that test each of the above assertions individually. Even though the basics of the tests are here, it possible more components for the test class are needed.

2021-12-07 20:32 UTC, MXHJohn314 commented
Line 6 does not pass the checkstyle. Change `import static org.junit.jupiter.api.Assertions.*;` to:
`import static org.junit.jupiter.api.Assertions.assertTrue;`
`import static org.junit.jupiter.api.Assertions.assertEquals;`

2021-12-07 22:10 UTC, jody requested changes
Please see inline review comments.

Note that Checkstyle reports errors. Please fix.

Please also demonstrate running this test, such as with a transcript. Attempts to run the test have resulted in run-time errors. Is that an expected outcome of the test, asserting that `StarGenerator` does not work as intended?

2021-12-07 22:10 UTC, jody commented on src/swdmt/redistricting/StarGeneratorTest.java
> +                previousDistrict = currentDistrict;
Why is an object of type `Location` referred to as a _district_ (`previousDistrict`,`currentDistrict`)?
This code is not intuitive so needs explanation or rewriting.
Is the intent to show that no two districts are identical? (Does this suggest we need an `equals` predicate defined for the `District` class?)
Is the intent to show that no district contains two identical locations? (Could we use some existing `contains` method or some Set operation?)

2021-12-07 22:10 UTC, jody commented on src/swdmt/redistricting/StarGeneratorTest.java
> +            assertEquals(patternSet.size(), pattern.size());
What is the meaning of this code? How does it test StarGenerator?

It appears to confirm that the [`size()`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/ArrayList.html#size()) method of [ArrayList](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/ArrayList.html) returns the value specified in the API: "Returns the number of elements in this list."

Perhaps this code needs additional explanation to get at some subtlety that isn't intuitively obvious.

2021-12-07 22:12 UTC, jody commented on src/swdmt/redistricting/StarGeneratorTest.java
> +    void generatePatternTest() {
The test needs `public` visibility.

2021-12-11 01:07 UTC, jody commented
Setting status to Draft; please advise when this is ready for review.

2021-12-23 17:25 UTC, jody commented
Incomplete. No activity in 16 days. Closing.

2021-12-23 17:25 UTC, closed without merging