Add StarGeneratorTest.java
MetroCS/redistricting pull request #187
Opened 2022-04-27 22:58 UTC by jsachetti

Added StarGeneratorTest.java to src/metrocs/redistricting, tests StarGenerator.java with JUnit
One method, generatePatternTest tests whether a null value is returned from the StarGenerator generatePattern method with inputs of 1 and 4, and tests if 2 patterns with same input are equal.
Ant build successful and no checkstyle errors on our machines.
- #129

2022-04-27 23:21 UTC, jody requested changes

2022-04-27 23:21 UTC, jody commented on src/metrocs/redistricting/StarGeneratorTest.java
> +        ArrayList<ArrayList<Location>> secondLocation = new ArrayList<ArrayList<Location>>();
Confusing variable names. The use of "...Location" suggests that the variable is holding a reference to a Location object, but that isn't the case.

What is the intent of the initializations? The values assigned don't appear to be used anywhere.

2022-04-27 23:21 UTC, jody commented on src/metrocs/redistricting/StarGeneratorTest.java
> +        assertEquals(firstLocation,secondLocation);
Why should these return "equal" values?
Where in the documentation is it specified that elements be in the same order in the ArrayList objects?

2022-04-27 23:45 UTC, DanielShermanSchool commented
Updated class to remove ambiguous tests, we're focusing on having a test foundation with a simple testing method to interface with JUnit.

2022-04-30 04:55 UTC, jody commented on src/metrocs/redistricting/StarGeneratorTest.java
> +        //check if method returns null
This is a vacuous comment in that it doesn't add any additional explanation to the code that isn't obvious by reading the code itself. The information delivered by this comment should be **why** this is checking whether or not the method returns null.

2022-04-30 04:57 UTC, jody requested changes
Overall looks fine, just a problem with the internal code comment which might also reflect a problem with the name of the test method.

2022-04-30 04:57 UTC, jody commented on src/metrocs/redistricting/StarGeneratorTest.java
> +    public void generatePatternTest() {
This method name indicates that this is a more complete test of the method. Perhaps it should be renamed to be more specific as to what is being tested/affirmed.

2022-06-08 19:20 UTC, jody commented
No update in over 30 days. Changing status to draft.

If no further updates in the next 14 days or if new PR addresses issue will delete.

2022-06-26 02:10 UTC, closed without merging