Setting up support for version link issue 171
MetroCS/redistricting pull request #190
Opened 2022-04-27 23:14 UTC by raffayqamar

Contributing to issue 171:

We created a "build.properties" file and made some changes to the "build.xml" file. Within the "build.properties" file we added a site name variable, release version and the "nameofrelease". Within the "build.xml" file we added a handler for our properties file that when invoked with a keyword info, it displays the website URL, the release version, and the "name of the release."

2022-04-27 23:25 UTC, jody commented
Thank you for this contribution.
Am I correct that this constitutes **part** of a resolution to User Story #171 ?
Is there an intent to continue work via this PR (keeping it open) or to close it and have future work under new PR?

2022-04-27 23:42 UTC, raffayqamar commented
> Thank you for this contribution. Am I correct that this constitutes **part** of a resolution to User Story #171 ? Is there an intent to continue work via this PR (keeping it open) or to close it and have future work under new PR?

Issue 171 should not be closed but our work should be merged because it took care of a portion of the issue that needed to be done.

2022-04-30 04:43 UTC, jody requested changes

2022-04-30 04:43 UTC, jody commented on build.properties
> +#The Site Name
Why does this one line have a comment, but no other lines?

2022-04-30 04:43 UTC, jody commented on build.xml
> +    <!--This sets up the build.properties file. Displays ant verison, site name, release verison, and name of the release-->
This comment doesn't seem appropriate. The build.properties file needs to be set up outside the automated build process. This target appears to only display the contents of an existing build.properties file.

2022-06-26 03:49 UTC, jody commented
(No response in 17 days.)
Thank you for this contribution which prompted PR #196 that builds on this work and replaces this PR.

2022-06-26 03:49 UTC, closed without merging