Initial test class created for StarGenerator
MetroCS/redistricting pull request #202
Opened 2023-10-17 18:34 UTC by ColinLouis95

StarGeneratorTest.java created with three methods for testing the StarGenerator class

2023-10-18 00:36 UTC, jody commented
When making a pull request, please include evidence that the changes have been reviewed and validated. This could include a transcript of the build and tests being run. and may include comments made by a reviewer (someone who wasn't involved in the development itself).

2023-10-18 00:45 UTC, jody reviewed
I'm unsure whether these tests are appropriate to the (admittedly vague) specifications of StarGenerator. Specific comments made on associated lines.

2023-10-18 00:45 UTC, jody commented on src/metrocs/redistricting/StarGeneratorTest.java
> +        assertEquals(sp, sp2);
Why do sp and sp2 need to be equal to each other? Is there a specification associated with StarGenerator that indicates that order in the returned list is significant?

2023-10-18 00:45 UTC, jody commented on src/metrocs/redistricting/StarGeneratorTest.java
> +    /** Verifies that the intial location start point for the pattern is 0,0 */
Is there a requirement that the first item in the returned collection (list) must be at coordinates 0,0?
Why isn't it sufficient for 0,0 to be just one of the locations in the returned collection?

2023-10-18 00:45 UTC, jody commented on src/metrocs/redistricting/StarGeneratorTest.java
> +    /** Verifies that locations inside pattern generated are not empty */
What is the defined behavior for StarGenerator with a parameter of 0?
Is the result empty? null? throws and exception?

2023-10-18 03:50 UTC, jody commented on src/metrocs/redistricting/StarGeneratorTest.java
> +    /** Verifies that the Star Generator method is not randomly generating a pattern */
Is there a requirement that the patterns returned by StarGenerator are presented in a specific order? The inherited "equals" method of ArrayList (from AbstractList) requires both lists to have the same elements in the same order.

2023-11-02 18:38 UTC, jody commented
Any progress? This PR seems stale. Do you want to close it?

2023-11-02 21:29 UTC, rjbeer commented
@jody  The test class has been updated and is ready to be reviewed.

2023-11-04 05:13 UTC, jody commented
Please squash commits so I am only seeing a single commit. Thanks!

2023-11-04 22:02 UTC, jody requested changes
Please address in-line feedback on individual test case documentation.

Please check that the code matches the project's conventions.
You can use the command `ant checkstyle` and then state it's results in a comment to this PR.

Also please include a transcript of running the product's test suite (ensuring no regression and demonstrating the functionality of the new test class).
You can use the command: `ant test`

2023-11-07 20:54 UTC, closed without merging